#!/bin/sh

source ./bootstrap_utils

chmod 700 ~/.cache ~/.config

__log_debug "decrypting secrets..."

yadm decrypt

__load_module nvm

system_type=$(uname -s)
__log_debug "targetting platform ${system_type}"

if [ $system_type = "Darwin" ]; then
  pwd
  __load_module xcode
  __load_module brew

  # TODO:
  # check if dependencies are not installed and try to automaticall install them
fi

source ./bootstrap_utils --unload
