#!/bin/sh

chmod 700 ~/.cache ~/.config

source ./bootstrap_utils

__load_module decrypt_secrets
__load_module nvm
__load_module xcode
__load_module brew
__load_module macos

  # TODO:
  # check if dependencies are not installed and try to automaticall install them

source ./bootstrap_utils --unload
