name: ShellCheck

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  shellcheck:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: '.config/yadm/encrypt'
          scandir: '.config/yadm'
        env:
          SHELLCHECK_OPTS: -e SC1090
